// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgx-L5uILtAURBBeGikrIvOISd18VT9Kg',
    appId: '1:709533276257:web:b0dc276b2a4a2d49d4b220',
    messagingSenderId: '709533276257',
    projectId: 'chat-a-1263b',
    authDomain: 'chat-a-1263b.firebaseapp.com',
    storageBucket: 'chat-a-1263b.appspot.com',
    measurementId: 'G-2VSX09P63B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hpaN9A509ugkCAi94HSRi9Jx5JH_8ac',
    appId: '1:709533276257:android:b79975ef1153983ed4b220',
    messagingSenderId: '709533276257',
    projectId: 'chat-a-1263b',
    storageBucket: 'chat-a-1263b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfl4p4UtJo_Ym6kbG4hNpivrOlOu0NeP0',
    appId: '1:709533276257:ios:c3fd5c05ef08aebbd4b220',
    messagingSenderId: '709533276257',
    projectId: 'chat-a-1263b',
    storageBucket: 'chat-a-1263b.appspot.com',
    iosBundleId: 'com.example.chitChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfl4p4UtJo_Ym6kbG4hNpivrOlOu0NeP0',
    appId: '1:709533276257:ios:c3fd5c05ef08aebbd4b220',
    messagingSenderId: '709533276257',
    projectId: 'chat-a-1263b',
    storageBucket: 'chat-a-1263b.appspot.com',
    iosBundleId: 'com.example.chitChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgx-L5uILtAURBBeGikrIvOISd18VT9Kg',
    appId: '1:709533276257:web:7e84e7a4fdc755c0d4b220',
    messagingSenderId: '709533276257',
    projectId: 'chat-a-1263b',
    authDomain: 'chat-a-1263b.firebaseapp.com',
    storageBucket: 'chat-a-1263b.appspot.com',
    measurementId: 'G-RF8800ESPN',
  );
}
